### ISSUE TITLE
[BUG] The GUI does not allow negative values in key parameter boxes

### ISSUE THREAD

**Issue by AdrianAriasAbreu** [brainglobe/brainreg#192]
**Describe the bug**
The default parameters in the Graphical User Interface (GUI) do not match with those in the Command Line Interface (CLI), resulting in inconsistent alignment outcomes depending on whether alignment is computed through the GUI or CLI.

Based on the documentation negative values set the units in pixels while positive values set values in millimeters (mm). 
https://brainglobe.info/documentation/brainreg/user-guide/parameters.html

The real issue is that the GUI only accepts positive values for parameters like **grid_spacing**, **smoothing_sigma_reference**, and **smoothing_sigma_floating**, making it impossible to input negative values.

**To Reproduce**
Compute any alignment in CLI and GUI and then compare the outcomes. 

**Expected behaviour**
Same outcomes regardless the use of CLI or GUI.

**Log file**
[brainreg_2024-04-26_09-49-50_CLI.log](https://github.com/brainglobe/brainreg/files/15160577/brainreg_2024-04-26_09-49-50_CLI.log)
[brainreg_2024-04-26_10-16-26_GUI.log](https://github.com/brainglobe/brainreg/files/15160578/brainreg_2024-04-26_10-16-26_GUI.log)

Key parameters when using CLI:
- grid_spacing: -10
- smoothing_sigma_reference: -1.0
- smoothing_sigma_floating: -1.0

Key parameters when using GUI:
- grid_spacing: 10
- smoothing_sigma_reference: 1
- smoothing_sigma_floating: 1.0

**Screenshots**
Alignment when using CLI
![image](https://github.com/brainglobe/brainreg/assets/64906929/bdf5ec8a-f85a-407f-b19c-dd9bf5af45cf)
Alignment when using GUI
![image](https://github.com/brainglobe/brainreg/assets/64906929/8948bc48-53f2-4578-b620-0f1ea65b3fde)

**Computer used**
- OS: Windows 10 Pro

**Conclusion**
The GUI does not allow negative values in the parameter boxes for grid_spacing, smoothing_sigma_reference, and smoothing_sigma_floating.

**Comment by adamltyson** [comment]
Thanks for raising this @AdrianAriasAbreu. Having looked into this, the plugin was actually making these parameters negative when running the registration. The UI was incorrect and confusing though, so I've corrected this in #193 to match the CLI. 

I also noticed another small difference between the napari plugin and the CLI when it comes to downsampling data. I think this explains the differences you see, not the parameter issue. This is also fixed in #193. On some test data of mine, this makes the GUI and CLI produce the same results, so I would be interested to see the results on your data too.
