### ISSUE TITLE
Does Brainreg not work with images with are >2048 pixels in xy?

### ISSUE THREAD

**Issue by Eddymorphling** [brainglobe/brainreg#214]
Hi folks, 
I am running the brainmapper CLI for registration and segmentation. I came across this error during the registration step

```
[NiftyReg ERROR] Function: reg_tools_kernelConvolution_core
[NiftyReg ERROR] This function does not support images with dimension > 2048
[NiftyReg] Exit here. File: /home/adam/Desktop/niftyreg_source/reg-lib/cpu/_reg_tools.cpp:1114

```

Does NiftyReg not support images > 2048 pixels in xy? Its true that my datasets are >2048 pixels in xy. Any workaround for this? Thanks!

**Comment by adamltyson** [comment]
brainreg supports arbitrarily large images, however when downsampled they need to be <2048 pixels. This is not usually a problem. This error message usually occurs when either the resolution of the orientation of your data is not set correctly. I would double check this is correct.

It's also possible that your data is larger than it should be, due to either:
- Lots of blank space around the brain, so I would suggest cropping the images
- Lots of tissue swelling due to tissue clearing, and I would suggest using "ideal", or in-vivo voxel sizes.

General advice though would be to double and triple check the parameters used. 

I'll close this issue now, but if you have any problems, let us know, either here, or on image.sc
