### ISSUE TITLE
how to change the factor of downsample ?

### ISSUE THREAD

**Issue by cindy12-gao** [brainglobe/brainreg#35]
hi adam,
     i want to improve the resolution of registered signal channel(in the registration folder), so how to change the factor of downsample?     the --affine n steps? or others?  
     hope for your answer~

**Comment by adamltyson** [comment]
Hi,

The registration will always be done at the resolution of the atlas that you choose (eg 10, 25, 50 or 100um for mouse). If you need the files at a higher resolution, they will need to be upsampled. 

By the way, we've now joined the image.sc forum (https://forum.image.sc/tag/brainglobe). If you have any more questions (I.e not bug reports) could you raise them on that forum and tag both "brainglobe" and the tool you're using (eg "brainreg") so that I'll see it. Then everyone can see and benefit from the answer. Thanks!
