### ISSUE TITLE
Save atlas in the same orientation as input data

### ISSUE THREAD

**Issue by JulesScholler** [brainglobe/brainreg#40]
The registered atlas file is always saved in the same orientation. I understand this can be useful for some applications but in the most common case where you want to analyse your data by overlaying the atlas onto the data it is quite cumbersome because one has to track the input orientation throughout the analysis pipeline.

Is there a possibility to save the registered atlas in the same orientation as the input data?

Thanks for your help and this amazing work :).

**Comment by adamltyson** [comment]
Hi @JulesScholler,

I chose to save everything in the same orientation as the atlas for three reasons:
* Usually the very final aim of these analyses is to get data into a common coordinate (i.e. atlas) space
* Comparing results in atlas & sample space with two different orientations is complicated
* brainreg is used by other software, and there needs to be a standard convention

I'm hesitant to make brainreg save the results in the same orientation as the input data because either:
* It's in addition to the existing results and data volumes double
* It's instead of the existing results, and everything else that brainreg depends on, breaks.

However, I can see how this would be useful, and there are a few ways of doing this. Do you have any thoughts on the following:
* Providing instructions on how to reorient things (e.g. using [bg-space](https://github.com/brainglobe/bg-space)). This has the benefit of flexibility, but is an additional step to the workflow.
* Making it easier to view data in the same orientation as the raw data, e.g. by adding options to the napari plugin. This could also rescale the data to the original resolution of the raw data. This is currently implemented in the cellfinder napari plugin. This has the benefit of not creating any more files, and allowing the results to be directly overlaid on the raw data at full resolution. The downside is that you wouldn't have the files on disk to work with in other software.
* Adding a flag (e.g. `--save-original-orientation`) that would optionally save some of the files in the original orientation. This would simplify downstream analyses in different software, but would increase the size of the output data (a problem with high-res atlases) and may not be too useful, as the data would be at an arbitrary resolution (that of the atlas). We would also need to decide what files would be needed to be exported. 
   
Long answer, but I'd be interested to know your thoughts, and more details about your use case.

**Comment by JulesScholler** [comment]
Hi @adamltyson,

Thanks for your detailed answer. I understand your points, and the way I saw things was close to your third point:

- Add an option/flag to save files in the original orientation (but at atlas resolution!) but make the default one work as it is now. Doing that you avoid breaking any downstream processing and you save space by only saving a single orientation.

My use case is pretty simple, I use the atlas as a map to quantify things is certain brain regions. E.g. count cells or compute the mean intensity. Usually I stitch a volume and register it to the atlas, I then use the atlas as a mask to guide the segmentation or analyse only certain part of the brain. For my use case it is ok to keep track of the orientation but I know people (non-programming scientists) who would benefit from this because they use brainreg in their pipeline. Of course I can add it myself and rotate back to the original orientation before saving but then I lose napari support and futur updates, hence my question.

I was not aware that bg-space could provide a way to smoothly reorient things, I will take a look!

**Comment by adamltyson** [comment]
Ok sounds good, so would it work for you to have an option to save `registered_atlas.tiff` and `registered_hemispheres.tiff` with the same orientation as the raw data?

**Comment by JulesScholler** [comment]
This will be perfect!

**Comment by JulesScholler** [comment]
@adamltyson any news about the implementation of a ```--save-original-orientation``` flag? If needed I can send a pull request when I have time to add it.

Cheers

**Comment by adamltyson** [comment]
Hi @JulesScholler, no progress yet. A PR would be very welcome!

**Comment by adamltyson** [comment]
Fixed by @JulesScholler  in #47 :tada:
